workspace:
  path: src

pipeline:
  build:
    image: node
    commands:
      - make install
      - make build
      - make release

  release:
    image: plugins/s3
    path_style: true
    strip_prefix: dist/
    source: dist/*
    target: /theme/master
    when:
      event: [ push ]
      branch: [ master ]

  downstream:
    image: plugins/downstream
    server: https://drone.gitea.io
    repositories:
      - go-gitea/website
      - go-gitea/blog
      - go-gitea/docs
      - go-gitea/redirects
    when:
      event: push
      branch: master

  gitter:
    image: plugins/gitter
