workspace:
  path: src

pipeline:
  build:
    image: library/node:latest
    commands:
      - npm install -q
      - npm run clean
      - npm run build
      - npm run release

  release:
    image: plugins/s3
    path_style: true
    strip_prefix: dist/
    source: dist/master.tar.gz
    target: /theme
    when:
      event: [ push ]
      branch: [ master ]

  trigger:
    image: plugins/downstream
    server: https://drone.gitea.io
    repositories:
      - go-gitea/website
      - go-gitea/blog
      - go-gitea/docs
      - go-gitea/redirects
    when:
      event: [ push ]
      branch: [ master ]

  gitter:
    image: plugins/gitter
